---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: reddit
    component: mongo
    comment-db: "true"
    post-db: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: reddit
        component: mongo
        comment-db: "true"
        post-db: "true"
    spec:
      containers:
      - image: mvertes/alpine-mongo:4.0.0-0
        name: mongo
        volumeMounts:
          # - name: mongo-gce-pd-storage
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
        #        # - name: mongo-persistent-storage
        #        # emptyDir: {}
        #        - name: mongo-gce-pd-storage
        #          gcePersistentDisk:
        #            pdName: reddit-mongo-disk
        #            fsType: ext4
        - name: mongo-persistent-storage
          persistentVolumeClaim: 
          # claimName: mongo-pvc
            claimName: mongo-pvc-dynamic
